#!/bin/bash

echo "🎨 成就系统组件 - 完整内容显示"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📄 1. LevelDisplay.tsx - 等级展示组件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
wc -l "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/LevelDisplay.tsx"
echo ""
echo "前30行预览："
head -30 "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/LevelDisplay.tsx"
echo ""
read -p "按Enter继续查看下一个组件..."

echo ""
echo "📄 2. SBTGallery.tsx - SBT展示墙组件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
wc -l "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/SBTGallery.tsx"
echo ""
echo "前30行预览："
head -30 "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/SBTGallery.tsx"
echo ""
read -p "按Enter继续查看下一个组件..."

echo ""
echo "📄 3. ClaimSBTFlow.tsx - 申领流程组件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
wc -l "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/ClaimSBTFlow.tsx"
echo ""
echo "前30行预览："
head -30 "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/ClaimSBTFlow.tsx"
echo ""
read -p "按Enter继续查看下一个组件..."

echo ""
echo "📄 4. ChainSwitcher.tsx - 链切换组件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
wc -l "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/ChainSwitcher.tsx"
echo ""
echo "完整内容："
cat "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/ChainSwitcher.tsx"
echo ""
read -p "按Enter继续查看下一个组件..."

echo ""
echo "📄 5. DualChainStatus.tsx - 双链对比组件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
wc -l "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/DualChainStatus.tsx"
echo ""
echo "前30行预览："
head -30 "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/DualChainStatus.tsx"
echo ""
read -p "按Enter继续..."

echo ""
echo "📄 6. index.ts - 组件导出索引"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat "/Users/jasoncong/Desktop/claude code/黑客松项目-证道/components/achievement/index.ts"
echo ""

echo "✅ 所有组件都已展示完毕！"
